package metier;
// Generated Mar 18, 2020 11:52:06 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Groupe generated by hbm2java
 */
public class Groupe  implements java.io.Serializable {


     private String idGroupe;
     private String nomGroupe;
     private Date dateDeb;
     private Date dateFin;
     private Set creaneaus = new HashSet(0);
     private Set personnels = new HashSet(0);

    public Groupe() {
    }

	
    public Groupe(String idGroupe, String nomGroupe, Date dateDeb, Date dateFin) {
        this.idGroupe = idGroupe;
        this.nomGroupe = nomGroupe;
        this.dateDeb = dateDeb;
        this.dateFin = dateFin;
    }
    public Groupe(String idGroupe, String nomGroupe, Date dateDeb, Date dateFin, Set creaneaus, Set personnels) {
       this.idGroupe = idGroupe;
       this.nomGroupe = nomGroupe;
       this.dateDeb = dateDeb;
       this.dateFin = dateFin;
       this.creaneaus = creaneaus;
       this.personnels = personnels;
    }
   
    public String getIdGroupe() {
        return this.idGroupe;
    }
    
    public void setIdGroupe(String idGroupe) {
        this.idGroupe = idGroupe;
    }
    public String getNomGroupe() {
        return this.nomGroupe;
    }
    
    public void setNomGroupe(String nomGroupe) {
        this.nomGroupe = nomGroupe;
    }
    public Date getDateDeb() {
        return this.dateDeb;
    }
    
    public void setDateDeb(Date dateDeb) {
        this.dateDeb = dateDeb;
    }
    public Date getDateFin() {
        return this.dateFin;
    }
    
    public void setDateFin(Date dateFin) {
        this.dateFin = dateFin;
    }
    public Set getCreaneaus() {
        return this.creaneaus;
    }
    
    public void setCreaneaus(Set creaneaus) {
        this.creaneaus = creaneaus;
    }
    public Set getPersonnels() {
        return this.personnels;
    }
    
    public void setPersonnels(Set personnels) {
        this.personnels = personnels;
    }




}


