package metier;
// Generated Mar 18, 2020 11:52:06 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Matiere generated by hbm2java
 */
public class Matiere  implements java.io.Serializable {


     private String libelleMatiere;
     private Ue ue;
     private Set personnels = new HashSet(0);
     private Set creaneaus = new HashSet(0);

    public Matiere() {
    }

	
    public Matiere(String libelleMatiere, Ue ue) {
        this.libelleMatiere = libelleMatiere;
        this.ue = ue;
    }
    public Matiere(String libelleMatiere, Ue ue, Set personnels, Set creaneaus) {
       this.libelleMatiere = libelleMatiere;
       this.ue = ue;
       this.personnels = personnels;
       this.creaneaus = creaneaus;
    }
   
    public String getLibelleMatiere() {
        return this.libelleMatiere;
    }
    
    public void setLibelleMatiere(String libelleMatiere) {
        this.libelleMatiere = libelleMatiere;
    }
    public Ue getUe() {
        return this.ue;
    }
    
    public void setUe(Ue ue) {
        this.ue = ue;
    }
    public Set getPersonnels() {
        return this.personnels;
    }
    
    public void setPersonnels(Set personnels) {
        this.personnels = personnels;
    }
    public Set getCreaneaus() {
        return this.creaneaus;
    }
    
    public void setCreaneaus(Set creaneaus) {
        this.creaneaus = creaneaus;
    }




}


