package metier;
// Generated 16 mars 2020 19:48:09 by Hibernate Tools 4.3.1



/**
 * Utilisateur generated by hbm2java
 */
public class Utilisateur  implements java.io.Serializable {


     private int codeU;
     private String nomU;
     private String prenomU;
     private String typeU;
     private String identifiant;
     private String password;

    public Utilisateur() {
    }

    public Utilisateur(int codeU, String nomU, String prenomU, String typeU, String identifiant, String password) {
       this.codeU = codeU;
       this.nomU = nomU;
       this.prenomU = prenomU;
       this.typeU = typeU;
       this.identifiant = identifiant;
       this.password = password;
    }

    public Utilisateur(String nomU, String prenomU, String identifiant, String password) {
        this.nomU = nomU;
        this.prenomU = prenomU;
        this.identifiant = identifiant;
        this.password = password;
    }
    
   
    public int getCodeU() {
        return this.codeU;
    }
    
    public void setCodeU(int codeU) {
        this.codeU = codeU;
    }
    public String getNomU() {
        return this.nomU;
    }
    
    public void setNomU(String nomU) {
        this.nomU = nomU;
    }
    public String getPrenomU() {
        return this.prenomU;
    }
    
    public void setPrenomU(String prenomU) {
        this.prenomU = prenomU;
    }
    public String getTypeU() {
        return this.typeU;
    }
    
    public void setTypeU(String typeU) {
        this.typeU = typeU;
    }
    public String getIdentifiant() {
        return this.identifiant;
    }
    
    public void setIdentifiant(String identifiant) {
        this.identifiant = identifiant;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }




}


